### ISSUE TITLE
Genauigkeit in der Testklasse nicht als Konstante definiert

### ISSUE THREAD

**Issue by jenskohler** [tpe-lecture/repo-09#3]
Genauigkeit in der Testklasse nicht als Konstante definiert
[- 5 Punkte]

**Comment by YasinTuna** [comment]
double genauigkeit = 0.00001;
was ist dann das?

**Comment by jenskohler** [comment]
Konstanten schreibt man groß (s. a. Code Conventions)

**Comment by YasinTuna** [comment]
Dann ist es doch nur ein Schönheitsfehler.. weil die idee der konstante war da
